---
- hosts: all
  become: yes
  tasks:
    - name: update hosts file
      blockinfile:
        path: /etc/hosts
        block: |
         172.31.42.125 lb01
         172.31.32.110 app01
         172.31.34.195 mq01
         172.31.41.67 mc01
         172.31.41.227 db01
